//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemtinhhaophi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Congtrinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Congtrinh()
        {
            this.Congtrinh_Congviec = new HashSet<Congtrinh_Congviec>();
        }
    
        public int Macongtrinh { get; set; }
        public string Tencongtrinh { get; set; }
        public string Tenchudautu { get; set; }
        public string Tonggiatri { get; set; }
        public string Diadiemcongtrinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Congtrinh_Congviec> Congtrinh_Congviec { get; set; }
    }
}
