//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemtinhhaophi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dinhmuc
    {
        public int Macongviec { get; set; }
        public int Mavattu { get; set; }
        public string Soluong { get; set; }
    
        public virtual Congviec Congviec { get; set; }
        public virtual Vattu Vattu { get; set; }
    }
}
