//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phanmemtinhhaophi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vattu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vattu()
        {
            this.Dinhmucs = new HashSet<Dinhmuc>();
        }
    
        public int Mavattu { get; set; }
        public string Tenvattu { get; set; }
        public string Quycach { get; set; }
        public string Donvitinh { get; set; }
        public string Dongia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dinhmuc> Dinhmucs { get; set; }
    }
}
